# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/hefftorlinux/landscape7.png'

# Special
background='#0e1025'
foreground='#c1ccd7'
cursor='#c1ccd7'

# Colors
color0='#0e1025'
color1='#6F6883'
color2='#8D7889'
color3='#A88B91'
color4='#AD9094'
color5='#B3B8BE'
color6='#86A5C2'
color7='#c1ccd7'
color8='#878e96'
color9='#6F6883'
color10='#8D7889'
color11='#A88B91'
color12='#AD9094'
color13='#B3B8BE'
color14='#86A5C2'
color15='#c1ccd7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
