--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/hefftorlinux/landscape7.png"

-- Special
background="#0e1025"
foreground="#c1ccd7"
cursor="#c1ccd7"

-- Colors
color0="#0e1025"
color1="#6F6883"
color2="#8D7889"
color3="#A88B91"
color4="#AD9094"
color5="#B3B8BE"
color6="#86A5C2"
color7="#c1ccd7"
color8="#878e96"
color9="#6F6883"
color10="#8D7889"
color11="#A88B91"
color12="#AD9094"
color13="#B3B8BE"
color14="#86A5C2"
color15="#c1ccd7"
